"""
Django settings for genai_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
env_path = BASE_DIR / '.env'
load_dotenv(env_path)

if env_path.exists():
    print(f"✅ .env file loaded from: {env_path}")
else:
    print(f"⚠️  .env file not found at: {env_path}")
    # Try parent directory
    parent_env = BASE_DIR.parent / '.env'
    if parent_env.exists():
        load_dotenv(parent_env)
        print(f"✅ .env file loaded from parent: {parent_env}")
    else:
        print(f"❌ .env file not found at: {parent_env}")

# env = environ.Env()
# environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
# Azure AI Configuration - Using os.getenv() instead of env()
AZURE_INFERENCE_ENDPOINT = os.getenv("AZURE_INFERENCE_ENDPOINT")
AZURE_INFERENCE_API_KEY = os.getenv("AZURE_INFERENCE_API_KEY")
AZURE_INFERENCE_MODEL = os.getenv("AZURE_INFERENCE_MODEL", "Llama-4-Maverick-17B-128E-Instruct-FP8-prochurn-demo")
AZURE_API_VERSION = os.getenv("AZURE_API_VERSION", "2024-05-01-preview")

# Debug Azure configuration
print("🔍 AZURE ENV CHECK:")
print(f"  ENDPOINT: {AZURE_INFERENCE_ENDPOINT}")
print(f"  MODEL: {AZURE_INFERENCE_MODEL}")
print(f"  API_VERSION: {AZURE_API_VERSION}")
if AZURE_INFERENCE_API_KEY:
    print(f"  API_KEY_LENGTH: {len(AZURE_INFERENCE_API_KEY)}")
    print(f"  API_KEY_PREVIEW: {AZURE_INFERENCE_API_KEY[:10]}...{AZURE_INFERENCE_API_KEY[-10:]}")
else:
    print("  API_KEY: ❌ NOT SET")

# Validate critical settings
missing_settings = []
if not AZURE_INFERENCE_ENDPOINT:
    missing_settings.append("AZURE_INFERENCE_ENDPOINT")
if not AZURE_INFERENCE_API_KEY:
    missing_settings.append("AZURE_INFERENCE_API_KEY")

if missing_settings:
    print(f"❌ Missing required environment variables: {missing_settings}")
    print("🔧 Please check your .env file")
else:
    print("✅ All Azure AI environment variables are set")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4f2f6wy^p$exq&n$8#o3s*ulm)g4n$v^yd-rt&_e1b46r19&6h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

from dotenv import load_dotenv
load_dotenv()


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'genai_app',
    'corsheaders',
    #  'django_extensions',
]

# INSTALLED_APPS += [
#     'corsheaders',
# ]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'genai_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'genai_app','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'genai_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'GenAI',
        'OPTIONS': {
            'options': '-c search_path=public'
        },
        'USER': 'postgres',
        'PASSWORD': 'Sandhiya@1127',
        'HOST': 'localhost',
        'PORT': '5432',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


# settings.py

# Allow large uploads (e.g. 1 GB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1 GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1 GB

CORS_ALLOW_ALL_ORIGINS = False  # Keep False for security

CORS_ALLOW_HEADERS = ["Authorization", "Content-Type"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True  # Important for sending cookies or auth headers

CSRF_TRUSTED_ORIGINS = [ 
    "http://localhost:3000",  # React dev server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",]  # Allow CSRF for frontend

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "DELETE", "OPTIONS",'PATCH',]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'cache-control',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# Expose headers to frontend
CORS_EXPOSE_HEADERS = [
    'Content-Disposition',
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


from decouple import config

# Load static DB credentials from .env
import os
from dotenv import load_dotenv
load_dotenv()

STATIC_DB = {
    "postgres_user": os.getenv("POSTGRES_USER"),
    "postgres_password": os.getenv("POSTGRES_PASSWORD"),
    "postgres_host": os.getenv("POSTGRES_HOST"),
    "postgres_port": os.getenv("POSTGRES_PORT", "5432"),
    "postgres_db": os.getenv("POSTGRES_DB"),
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'genai_app', 'static')]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
